name: Run Actionlint
on: 
  pull_request:
    branches: main
  
  workflow_call:
    
permissions:
  contents: read

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      # needed for the checkout action
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    steps: 
    # checkout the source code to analyze
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    # run the actionlinter
    - uses: devops-actions/actionlint@469810fd82c015d3c43815cd2b0e4d02eecc4819 # v0.1.11
      # trying to find a way to fail the workflow, but not block the PR, so far no luck with required workflows
      #continue-on-error: true
      
    #- if: failure()
    #  run: echo "here"    
